name: Arduino lint
on: [push, pull_request]

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v3
      
    - name: Check linting
      uses: arduino/arduino-lint-action@v1.0.2
      with:
        compliance: "permissive"
        project-type: "sketch"
        verbose: true
        recursive: true
        path: "./src/main.cpp"